### ISSUE TITLE
Flow + Spring + Polymer 3

### ISSUE THREAD

**Issue by devcsrj** [vaadin/flow-spring-tutorial#34]
Does Flow support Polymer 3? The current docs and this demo are all in Polymer 2, so I was wondering if this demo can be updated to a Polymer 3 example? What needs to be done for migration, if any?

**Comment by Legioth** [comment]
Flow does not work with Polymer 3 at this moment. We will provide support in the future, but the exact priorities and roadmaps have not yet been decided.

Updating the current demos to use Polymer 3 would be problematic because of various missing features, e.g.
* Loading JS Modules and integrating / emulating the runtime translations done to support bare imports and dynamic imports.
* Flow wouldn't know where to find the template files for analyzing e.g. `@Id` usage.
* Support for NPM webjars
